apiVersion: v1
kind: Deployment
metadata: 
  name: netology-ml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers: 
        - image: tomcat:8.5.69
          name: tomcat
          ports:
           - containerPort: 8080
